languages1={'Afrikans (South Africa)': 'af-ZA', 'Albanian (Albania)': 'sq-AL', 'Amharic (Ethiopia)': 'am-ET', 'Arabic (Algeria)': 'ar-DZ', 'Arabic (Bahrain)': 'ar-BH', 'Arabic (Egypt)': 'ar-EG', 'Arabic (Iraq)': 'ar-IQ', 'Arabic (Israel)': 'ar-IL', 'Arabic (Jordan)': 'ar-JO', 'Arabic (Kuwait)': 'ar-KW', 'Arabic (Lebanon)': 'ar-LB', 'Arabic (Mauritania)': 'ar-MR', 'Arabic (Morocco)': 'ar-MA', 'Arabic (Oman)': 'ar-OM', 'Arabic (Qatar)': 'ar-QA', 'Arabic (Saudi Arabia)': 'ar-SA', 'Arabic (State of Palestine)': 'ar-PS', 'Arabic (Tunisia)': 'ar-TN', 'Arabic (United Arab Emirates)': 'ar-AE', 'Arabic (Yemen)': 'ar-YE', 'Armenian (Armenia)': 'hy-AM', 'Azerbaijani (Azerbaijan)': 'az-AZ', 'Basque (Spain)': 'eu-ES', 'Bengali (Bangladesh)': 'bn-BD', 'Bengali (India)': 'bn-IN', 'Bosnian (Bosnia and Herzegovina)': 'bs-BA', 'Bulgarian (Bulgaria)': 'bg-BG', 'Burmese (Myanmar)': 'my-MM', 'Catalan (Spain)': 'ca-ES', 'Chinese, Cantonese (Traditional Hong Kong)': 'yue-Hant-HK', 'Chinese, Mandarin (Simplified, China)': 'zh (cmn-Hans-CN)', 'Chinese, Mandarin (Traditional, Taiwan)': 'zh-TW (cmn-Hant-TW)', 'Croatian (Croatia)': 'hr-HR', 'Czech (Czech Republic)': 'cs-CZ', 'Danish (Denmark)': 'da-DK', 'Dutch (Belgium)': 'nl-BE', 'Dutch (Netherlands)': 'nl-NL', 'English (Australia)': 'en-AU', 'English (Canada)': 'en-CA', 'English (Ghana)': 'en-GH', 'English (Hong Kong)': 'en-HK', 'English (India)': 'en-IN', 'English (Ireland)': 'en-IE', 'English (Kenya)': 'en-KE', 'English (New Zealand)': 'en-NZ', 'English (Nigeria)': 'en-NG', 'English (Pakistan)': 'en-PK', 'English (Philippines)': 'en-PH', 'English (Singapore)': 'en-SG', 'English (South Africa)': 'en-ZA', 'English (Tanzania)': 'en-TZ', 'English (United Kingdom)': 'en-GB', 'English (United States)': 'en-US', 'Estonian (Estonia)': 'et-EE', 'Filipino (Philippines)': 'fil-PH', 'Finnish (Finland)': 'fi-FI', 'French (Belgium)': 'fr-BE', 'French (Canada)': 'fr-CA', 'French (France)': 'fr-FR', 'French (Switzerland)': 'fr-CH', 'Galician (Spain)': 'gl-ES', 'Georgian (Georgia)': 'ka-GE', 'German (Austria)': 'de-AT', 'German (Germany)': 'de-DE', 'German (Switzerland)': 'de-CH', 'Greek (Greece)': 'el-GR', 'Gujarati (India)': 'gu-IN', 'Hebrew (Israel)': 'iw-IL', 'Hindi (India)': 'hi-IN', 'Hungarian (Hungary)': 'hu-HU', 'Icelandic (Iceland)': 'is-IS', 'Indonesian (Indonesia)': 'id-ID', 'Italian (Italy)': 'it-IT', 'Italian (Switzerland)': 'it-CH', 'Japanese (Japan)': 'ja-JP', 'Javanese (Indonesia)': 'jv-ID', 'Kannada (India)': 'kn-IN', 'Kazakh (Kazakhstan)': 'kk-KZ', 'Khmer (Cambodia)': 'km-KH', 'Korean (South Korea)': 'ko-KR', 'Lao (Laos)': 'lo-LA', 'Latvian (Latvia)': 'lv-LV', 'Lithuanian (Lithuania)': 'lt-LT', 'Macedonian (North Macedonia)': 'mk-MK', 'Malay (Malaysia)': 'ms-MY', 'Malayalam (India)': 'ml-IN', 'Marathi (India)': 'mr-IN', 'Mongolian (Mongolia)': 'mn-MN', 'Nepali (Nepal)': 'ne-NP', 'Norwegian Bokm책l (Norway)': 'no-NO', 'Persian (Iran)': 'fa-IR', 'Polish (Poland)': 'pl-PL', 'Portuguese (Brazil)': 'pt-BR', 'Portuguese (Portugal)': 'pt-PT', 'Punjabi (Gurmukhi India)': 'pa-Guru-IN', 'Romanian (Romania)': 'ro-RO', 'Russian (Russia)': 'ru-RU', 'Kinyarwanda (Rwanda)': 'rw-RW', 'Serbian (Serbia)': 'sr-RS', 'Sinhala (Sri Lanka)': 'si-LK', 'Slovak (Slovakia)': 'sk-SK', 'Slovenian (Slovenia)': 'sl-SI', 'Swati (South Africa)': 'ss-latn-za', 'Southern Sotho (South Africa)': 'st-ZA', 'Spanish (Argentina)': 'es-AR', 'Spanish (Bolivia)': 'es-BO', 'Spanish (Chile)': 'es-CL', 'Spanish (Colombia)': 'es-CO', 'Spanish (Costa Rica)': 'es-CR', 'Spanish (Dominican Republic)': 'es-DO', 'Spanish (Ecuador)': 'es-EC', 'Spanish (El Salvador)': 'es-SV', 'Spanish (Guatemala)': 'es-GT', 'Spanish (Honduras)': 'es-HN', 'Spanish (Mexico)': 'es-MX', 'Spanish (Nicaragua)': 'es-NI', 'Spanish (Panama)': 'es-PA', 'Spanish (Paraguay)': 'es-PY', 'Spanish (Peru)': 'es-PE', 'Spanish (Puerto Rico)': 'es-PR', 'Spanish (Spain)': 'es-ES', 'Spanish (United States)': 'es-US', 'Spanish (Uruguay)': 'es-UY', 'Spanish (Venezuela)': 'es-VE', 'Sundanese (Indonesia)': 'su-ID', 'Swahili (Kenya)': 'sw-KE', 'Swahili (Tanzania)': 'sw-TZ', 'Swedish (Sweden)': 'sv-SE', 'Tamil (India)': 'ta-IN', 'Tamil (Malaysia)': 'ta-MY', 'Tamil (Singapore)': 'ta-SG', 'Tamil (Sri Lanka)': 'ta-LK', 'Telugu (India)': 'te-IN', 'Thai (Thailand)': 'th-TH', 'Setswana (South Africa)': 'tn-latn-za', 'Turkish (Turkey)': 'tr-TR', 'Tsonga (South Africa)': 'ts-ZA', 'Ukrainian (Ukraine)': 'uk-UA', 'Urdu (India)': 'ur-IN', 'Urdu (Pakistan)': 'ur-PK', 'Uzbek (Uzbekistan)': 'uz-UZ', 'Venda (South Africa)': 've-ZA', 'Vietnamese (Vietnam)': 'vi-VN', 'isiXhosa (South Africa)': 'xh-ZA', 'Zulu (South Africa)': 'zu-ZA'}



languages={'Afrikaans': 'af', 
    'Akan': 'ak', 
    'Albanian': 'sq',
    'Amharic': 'am',
    'Arabic': 'ar',
    'Armenian': 'hy',
    'Assamese': 'as',
    'Aymara': 'ay',
    'Azerbaijani': 'az',
    'Bangla': 'bn',
    'Basque': 'eu',
    'Belarusian': 'be',
    'Bhojpuri': 'bho',
    'Bosnian': 'bs',
    'Bulgarian': 'bg',
    'Burmese': 'my',
    'Catalan': 'ca',
    'Cebuano': 'ceb',
    'Chinese (Simplified)': 'zh-Hans',
    'Chinese (Traditional)': 'zh-Hant',
    'Corsican': 'co', 'Croatian': 'hr',
    'Czech': 'cs', 'Danish': 'da',
    'Divehi': 'dv',
    'Dutch': 'nl',
    'English': 'en',
    'Esperanto': 'eo',
    'Estonian': 'et', 'Ewe': 'ee',
    'Filipino': 'fil', 'Finnish': 'fi',
    'French': 'fr',
    'Galician': 'gl',
    'Ganda': 'lg',
    'Georgian': 'ka',
    'German': 'de',
    'Greek': 'el',
    'Guarani': 'gn',
    'Gujarati': 'gu',
    'Haitian Creole': 'ht',
    'Hausa': 'ha',
    'Hawaiian': 'haw',
    'Hebrew': 'iw',
    'Hindi': 'hi', 'Hmong': 'hmn',
    'Hungarian': 'hu',
    'Icelandic': 'is',
    'Igbo': 'ig',
    'Indonesian': 'id',
    'Irish': 'ga',
    'Italian': 'it',
    'Japanese': 'ja',
    'Javanese': 'jv',
    'Kannada': 'kn',
    'Kazakh': 'kk',
    'Khmer': 'km',
    'Kinyarwanda': 'rw',
    'Korean': 'ko',
    'Krio': 'kri',
    'Kurdish': 'ku',
    'Kyrgyz': 'ky',
    'Lao': 'lo',
    'Latin': 'la',
    'Latvian': 'lv',
    'Lingala': 'ln',
    'Lithuanian': 'lt',
    'Luxembourgish': 'lb',
    'Macedonian': 'mk',
    'Malagasy': 'mg',
    'Malay': 'ms',
    'Malayalam': 'ml', 'Maltese': 'mt', 'Māori': 'mi', 'Marathi': 'mr', 'Mongolian': 'mn', 'Nepali': 'ne', 'Northern Sotho': 'nso', 'Norwegian': 'no', 'Nyanja': 'ny', 'Odia': 'or', 'Oromo': 'om', 'Pashto': 'ps', 'Persian': 'fa', 'Polish': 'pl', 'Portuguese': 'pt', 'Punjabi': 'pa', 'Quechua': 'qu', 'Romanian': 'ro', 'Russian': 'ru', 'Samoan': 'sm', 'Sanskrit': 'sa', 'Scottish Gaelic': 'gd', 'Serbian': 'sr', 'Shona': 'sn', 'Sindhi': 'sd', 'Sinhala': 'si', 'Slovak': 'sk', 'Slovenian': 'sl', 'Somali': 'so', 'Southern Sotho': 'st', 'Spanish': 'es', 'Sundanese': 'su', 'Swahili': 'sw', 'Swedish': 'sv', 'Tajik': 'tg', 'Tamil': 'ta', 'Tatar': 'tt', 'Telugu': 'te', 'Thai': 'th', 'Tigrinya': 'ti', 'Tsonga': 'ts', 'Turkish': 'tr', 'Turkmen': 'tk', 'Ukrainian': 'uk', 'Unknown Language': 'und', 'Urdu': 'ur', 'Uyghur': 'ug', 'Uzbek': 'uz', 'Vietnamese': 'vi', 'Welsh': 'cy', 'Western Frisian': 'fy', 'Xhosa': 'xh', 'Yiddish': 'yi', 
    'Yoruba': 'yo',
    'Zulu': 'zu'}
