# Generated by Django 4.0.2 on 2023-03-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('phone', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
